// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"errors"
	"net"

	"github.com/jackc/pgx/v5/pgxpool"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"

	"github.com/sanbei101/im/internal/db"
	"github.com/sanbei101/im/internal/worker"
	"github.com/sanbei101/im/pkg/config"
	proto "github.com/sanbei101/im/pkg/protocol"
)

// Injectors from wire.go:

func initializeWorkerApp(path string) (*App, func(), error) {
	config, err := provideConfig(path)
	if err != nil {
		return nil, nil, err
	}
	pool, cleanup, err := providePGXPool(config)
	if err != nil {
		return nil, nil, err
	}
	queries := provideQueries(pool)
	clientConn, cleanup2, err := provideGatewayConn(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	gatewayServiceClient := provideGatewayServiceClient(clientConn)
	publisher := provideDeliveryPublisher(gatewayServiceClient)
	workerWorker := provideWorker(queries, publisher)
	listener, err := provideGRPCListener(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	workerGRPCServer := provideWorkerGRPCServer(workerWorker)
	server := provideGRPCServer(workerGRPCServer)
	app := provideApp(config, workerWorker, server, listener)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func provideConfig(path string) (*config.Config, error) {
	return config.Load(path)
}

func providePGXPool(cfg *config.Config) (*pgxpool.Pool, func(), error) {
	if cfg.Postgres.DSN == "" {
		return nil, nil, errors.New("postgres.dsn is required for worker")
	}

	pool, err := pgxpool.New(context.Background(), cfg.Postgres.DSN)
	if err != nil {
		return nil, nil, err
	}
	if err := pool.Ping(context.Background()); err != nil {
		pool.Close()
		return nil, nil, err
	}
	return pool, pool.Close, nil
}

func provideQueries(pool *pgxpool.Pool) *db.Queries {
	return db.New(pool)
}

func provideGatewayConn(cfg *config.Config) (*grpc.ClientConn, func(), error) {
	conn, err := grpc.NewClient(cfg.Gateway.GRPCAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { _ = conn.Close() }, nil
}

func provideGatewayServiceClient(conn *grpc.ClientConn) proto.GatewayServiceClient {
	return proto.NewGatewayServiceClient(conn)
}

func provideDeliveryPublisher(client proto.GatewayServiceClient) worker.DeliveryPublisher {
	return worker.DeliveryPublisherFunc(func(ctx context.Context, envelope *worker.DeliveryEnvelope) error {
		_, err := client.DeliverMessage(ctx, &proto.DeliverMessageRequest{Message: envelope.Message})
		return err
	})
}

func provideWorker(queries *db.Queries, publisher worker.DeliveryPublisher) *worker.Service {
	return worker.New(worker.NewPostgresMessageStore(queries), publisher)
}

func provideGRPCListener(cfg *config.Config) (net.Listener, error) {
	return net.Listen("tcp", cfg.Worker.GRPCAddr)
}

func provideWorkerGRPCServer(w *worker.Service) *WorkerGRPCServer {
	return &WorkerGRPCServer{worker: w}
}

func provideGRPCServer(svc *WorkerGRPCServer) *grpc.Server {
	server := grpc.NewServer()
	proto.RegisterWorkerServiceServer(server, svc)
	return server
}

func provideApp(cfg *config.Config, w *worker.Service, grpcServer *grpc.Server, grpcListener net.Listener) *App {
	return &App{
		Config:       cfg,
		Worker:       w,
		GRPCServer:   grpcServer,
		GRPCListener: grpcListener,
	}
}
