// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Room struct {
	ID         int64            `json:"id"`
	Name       string           `json:"name"`
	CreateDate pgtype.Timestamp `json:"create_date"`
}

type RoomMember struct {
	ID         int64            `json:"id"`
	RoomID     int64            `json:"room_id"`
	UserID     int64            `json:"user_id"`
	JoinDate   pgtype.Timestamp `json:"join_date"`
	LastOnline pgtype.Timestamp `json:"last_online"`
}

type RoomMessage struct {
	ID        int64            `json:"id"`
	RoomID    int64            `json:"room_id"`
	UserID    int64            `json:"user_id"`
	Message   string           `json:"message"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID         int64            `json:"id"`
	Username   string           `json:"username"`
	Email      string           `json:"email"`
	Password   string           `json:"password"`
	CreateDate pgtype.Timestamp `json:"create_date"`
}
