// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const broadcastMessage = `-- name: BroadcastMessage :exec
SELECT pg_notify($1::text, $2::text)
`

type BroadcastMessageParams struct {
	Channel string `json:"channel"`
	Payload string `json:"payload"`
}

func (q *Queries) BroadcastMessage(ctx context.Context, arg BroadcastMessageParams) error {
	_, err := q.db.Exec(ctx, broadcastMessage, arg.Channel, arg.Payload)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO room (
    name
) VALUES (
    $1
)
RETURNING id, name, create_date
`

func (q *Queries) CreateRoom(ctx context.Context, name string) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, name)
	var i Room
	err := row.Scan(&i.ID, &i.Name, &i.CreateDate)
	return i, err
}

const createRoomMember = `-- name: CreateRoomMember :exec
INSERT INTO room_member (
    room_id,
    user_id
) VALUES (
    $1,
    $2
)
`

type CreateRoomMemberParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) CreateRoomMember(ctx context.Context, arg CreateRoomMemberParams) error {
	_, err := q.db.Exec(ctx, createRoomMember, arg.RoomID, arg.UserID)
	return err
}

const createRoomMessage = `-- name: CreateRoomMessage :exec
INSERT INTO room_message (
    room_id,
    user_id,
    message
) VALUES (
    $1,
    $2,
    $3
)
`

type CreateRoomMessageParams struct {
	RoomID  int64  `json:"room_id"`
	UserID  int64  `json:"user_id"`
	Message string `json:"message"`
}

func (q *Queries) CreateRoomMessage(ctx context.Context, arg CreateRoomMessageParams) error {
	_, err := q.db.Exec(ctx, createRoomMessage, arg.RoomID, arg.UserID, arg.Message)
	return err
}

const listRecentRoomMessages = `-- name: ListRecentRoomMessages :many
SELECT
    rm.room_id,
    rm.user_id,
    u.username,
    rm.message,
    rm.created_at
FROM room_message rm
JOIN users u ON rm.user_id = u.id
WHERE rm.room_id = $1
  AND rm.created_at >= NOW() - INTERVAL '1 hour'
ORDER BY rm.created_at ASC
`

type ListRecentRoomMessagesRow struct {
	RoomID    int64            `json:"room_id"`
	UserID    int64            `json:"user_id"`
	Username  string           `json:"username"`
	Message   string           `json:"message"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListRecentRoomMessages(ctx context.Context, roomID int64) ([]ListRecentRoomMessagesRow, error) {
	rows, err := q.db.Query(ctx, listRecentRoomMessages, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentRoomMessagesRow
	for rows.Next() {
		var i ListRecentRoomMessagesRow
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Username,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, create_date
FROM room
ORDER BY id ASC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(&i.ID, &i.Name, &i.CreateDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roomMemberExists = `-- name: RoomMemberExists :one
SELECT EXISTS (
    SELECT 1
    FROM room_member
    WHERE room_id = $1
      AND user_id = $2
)
`

type RoomMemberExistsParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RoomMemberExists(ctx context.Context, arg RoomMemberExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, roomMemberExists, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const touchRoomMember = `-- name: TouchRoomMember :exec
UPDATE room_member
SET last_online = NOW()
WHERE room_id = $1
  AND user_id = $2
`

type TouchRoomMemberParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) TouchRoomMember(ctx context.Context, arg TouchRoomMemberParams) error {
	_, err := q.db.Exec(ctx, touchRoomMember, arg.RoomID, arg.UserID)
	return err
}
