// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/model/proto/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_TEXT        MessageType = 1
	MessageType_MESSAGE_TYPE_IMAGE       MessageType = 2
	MessageType_MESSAGE_TYPE_VIDEO       MessageType = 3
	MessageType_MESSAGE_TYPE_FILE        MessageType = 4
	MessageType_MESSAGE_TYPE_SYSTEM      MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_TEXT",
		2: "MESSAGE_TYPE_IMAGE",
		3: "MESSAGE_TYPE_VIDEO",
		4: "MESSAGE_TYPE_FILE",
		5: "MESSAGE_TYPE_SYSTEM",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_TEXT":        1,
		"MESSAGE_TYPE_IMAGE":       2,
		"MESSAGE_TYPE_VIDEO":       3,
		"MESSAGE_TYPE_FILE":        4,
		"MESSAGE_TYPE_SYSTEM":      5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_model_proto_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_internal_model_proto_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_model_proto_message_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         []byte                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ClientMsgId   []byte                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	SenderId      []byte                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RoomId        []byte                 `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ReplyToMsgId  []byte                 `protobuf:"bytes,5,opt,name=reply_to_msg_id,json=replyToMsgId,proto3,oneof" json:"reply_to_msg_id,omitempty"`
	MsgType       MessageType            `protobuf:"varint,6,opt,name=msg_type,json=msgType,proto3,enum=im.proto.v1.MessageType" json:"msg_type,omitempty"`
	ServerTime    int64                  `protobuf:"varint,7,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Payload       []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	Ext           []byte                 `protobuf:"bytes,9,opt,name=ext,proto3,oneof" json:"ext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_model_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_model_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *Message) GetClientMsgId() []byte {
	if x != nil {
		return x.ClientMsgId
	}
	return nil
}

func (x *Message) GetSenderId() []byte {
	if x != nil {
		return x.SenderId
	}
	return nil
}

func (x *Message) GetRoomId() []byte {
	if x != nil {
		return x.RoomId
	}
	return nil
}

func (x *Message) GetReplyToMsgId() []byte {
	if x != nil {
		return x.ReplyToMsgId
	}
	return nil
}

func (x *Message) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetExt() []byte {
	if x != nil {
		return x.Ext
	}
	return nil
}

var File_internal_model_proto_message_proto protoreflect.FileDescriptor

const file_internal_model_proto_message_proto_rawDesc = "" +
	"\n" +
	"\"internal/model/proto/message.proto\x12\vim.proto.v1\"\xc9\x02\n" +
	"\aMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\fR\x05msgId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\fR\vclientMsgId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\fR\bsenderId\x12\x17\n" +
	"\aroom_id\x18\x04 \x01(\fR\x06roomId\x12*\n" +
	"\x0freply_to_msg_id\x18\x05 \x01(\fH\x00R\freplyToMsgId\x88\x01\x01\x123\n" +
	"\bmsg_type\x18\x06 \x01(\x0e2\x18.im.proto.v1.MessageTypeR\amsgType\x12\x1f\n" +
	"\vserver_time\x18\a \x01(\x03R\n" +
	"serverTime\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12\x15\n" +
	"\x03ext\x18\t \x01(\fH\x01R\x03ext\x88\x01\x01B\x12\n" +
	"\x10_reply_to_msg_idB\x06\n" +
	"\x04_ext*\xa2\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x01\x12\x16\n" +
	"\x12MESSAGE_TYPE_IMAGE\x10\x02\x12\x16\n" +
	"\x12MESSAGE_TYPE_VIDEO\x10\x03\x12\x15\n" +
	"\x11MESSAGE_TYPE_FILE\x10\x04\x12\x17\n" +
	"\x13MESSAGE_TYPE_SYSTEM\x10\x05B\x06Z\x04./pbb\x06proto3"

var (
	file_internal_model_proto_message_proto_rawDescOnce sync.Once
	file_internal_model_proto_message_proto_rawDescData []byte
)

func file_internal_model_proto_message_proto_rawDescGZIP() []byte {
	file_internal_model_proto_message_proto_rawDescOnce.Do(func() {
		file_internal_model_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_model_proto_message_proto_rawDesc), len(file_internal_model_proto_message_proto_rawDesc)))
	})
	return file_internal_model_proto_message_proto_rawDescData
}

var file_internal_model_proto_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_model_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_model_proto_message_proto_goTypes = []any{
	(MessageType)(0), // 0: im.proto.v1.MessageType
	(*Message)(nil),  // 1: im.proto.v1.Message
}
var file_internal_model_proto_message_proto_depIdxs = []int32{
	0, // 0: im.proto.v1.Message.msg_type:type_name -> im.proto.v1.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_model_proto_message_proto_init() }
func file_internal_model_proto_message_proto_init() {
	if File_internal_model_proto_message_proto != nil {
		return
	}
	file_internal_model_proto_message_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_model_proto_message_proto_rawDesc), len(file_internal_model_proto_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_model_proto_message_proto_goTypes,
		DependencyIndexes: file_internal_model_proto_message_proto_depIdxs,
		EnumInfos:         file_internal_model_proto_message_proto_enumTypes,
		MessageInfos:      file_internal_model_proto_message_proto_msgTypes,
	}.Build()
	File_internal_model_proto_message_proto = out.File
	file_internal_model_proto_message_proto_goTypes = nil
	file_internal_model_proto_message_proto_depIdxs = nil
}
