// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatType int32

const (
	ChatType_CHAT_TYPE_INVALID ChatType = 0
	ChatType_CHAT_TYPE_SINGLE  ChatType = 1
	ChatType_CHAT_TYPE_GROUP   ChatType = 2
	ChatType_CHAT_TYPE_ROOM    ChatType = 3
)

// Enum value maps for ChatType.
var (
	ChatType_name = map[int32]string{
		0: "CHAT_TYPE_INVALID",
		1: "CHAT_TYPE_SINGLE",
		2: "CHAT_TYPE_GROUP",
		3: "CHAT_TYPE_ROOM",
	}
	ChatType_value = map[string]int32{
		"CHAT_TYPE_INVALID": 0,
		"CHAT_TYPE_SINGLE":  1,
		"CHAT_TYPE_GROUP":   2,
		"CHAT_TYPE_ROOM":    3,
	}
)

func (x ChatType) Enum() *ChatType {
	p := new(ChatType)
	*p = x
	return p
}

func (x ChatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (ChatType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x ChatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatType.Descriptor instead.
func (ChatType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type SystemPayload_Action int32

const (
	SystemPayload_ACTION_UNSPECIFIED SystemPayload_Action = 0
	SystemPayload_ACTION_MSG_RECALL  SystemPayload_Action = 1
	SystemPayload_ACTION_GROUP_JOIN  SystemPayload_Action = 2
	SystemPayload_ACTION_GROUP_KICK  SystemPayload_Action = 3
)

// Enum value maps for SystemPayload_Action.
var (
	SystemPayload_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_MSG_RECALL",
		2: "ACTION_GROUP_JOIN",
		3: "ACTION_GROUP_KICK",
	}
	SystemPayload_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_MSG_RECALL":  1,
		"ACTION_GROUP_JOIN":  2,
		"ACTION_GROUP_KICK":  3,
	}
)

func (x SystemPayload_Action) Enum() *SystemPayload_Action {
	p := new(SystemPayload_Action)
	*p = x
	return p
}

func (x SystemPayload_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemPayload_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (SystemPayload_Action) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x SystemPayload_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemPayload_Action.Descriptor instead.
func (SystemPayload_Action) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10, 0}
}

type ChatMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MsgId       string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ClientMsgId string                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	SenderId    string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId  string                 `protobuf:"bytes,4,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ChatType    ChatType               `protobuf:"varint,5,opt,name=chat_type,json=chatType,proto3,enum=proto.ChatType" json:"chat_type,omitempty"`
	ServerTime  int64                  `protobuf:"varint,6,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatMessage_Text
	//	*ChatMessage_Image
	//	*ChatMessage_Voice
	//	*ChatMessage_Video
	//	*ChatMessage_File
	//	*ChatMessage_System
	Payload       isChatMessage_Payload `protobuf_oneof:"payload"`
	ReplyToMsgId  string                `protobuf:"bytes,20,opt,name=reply_to_msg_id,json=replyToMsgId,proto3" json:"reply_to_msg_id,omitempty"`
	Ext           map[string]string     `protobuf:"bytes,21,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ChatMessage) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *ChatMessage) GetChatType() ChatType {
	if x != nil {
		return x.ChatType
	}
	return ChatType_CHAT_TYPE_INVALID
}

func (x *ChatMessage) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *ChatMessage) GetPayload() isChatMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatMessage) GetText() *TextPayload {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ChatMessage) GetImage() *ImagePayload {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *ChatMessage) GetVoice() *VoicePayload {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_Voice); ok {
			return x.Voice
		}
	}
	return nil
}

func (x *ChatMessage) GetVideo() *VideoPayload {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_Video); ok {
			return x.Video
		}
	}
	return nil
}

func (x *ChatMessage) GetFile() *FilePayload {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *ChatMessage) GetSystem() *SystemPayload {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_System); ok {
			return x.System
		}
	}
	return nil
}

func (x *ChatMessage) GetReplyToMsgId() string {
	if x != nil {
		return x.ReplyToMsgId
	}
	return ""
}

func (x *ChatMessage) GetExt() map[string]string {
	if x != nil {
		return x.Ext
	}
	return nil
}

type isChatMessage_Payload interface {
	isChatMessage_Payload()
}

type ChatMessage_Text struct {
	Text *TextPayload `protobuf:"bytes,10,opt,name=text,proto3,oneof"`
}

type ChatMessage_Image struct {
	Image *ImagePayload `protobuf:"bytes,11,opt,name=image,proto3,oneof"`
}

type ChatMessage_Voice struct {
	Voice *VoicePayload `protobuf:"bytes,12,opt,name=voice,proto3,oneof"`
}

type ChatMessage_Video struct {
	Video *VideoPayload `protobuf:"bytes,13,opt,name=video,proto3,oneof"`
}

type ChatMessage_File struct {
	File *FilePayload `protobuf:"bytes,14,opt,name=file,proto3,oneof"`
}

type ChatMessage_System struct {
	System *SystemPayload `protobuf:"bytes,15,opt,name=system,proto3,oneof"`
}

func (*ChatMessage_Text) isChatMessage_Payload() {}

func (*ChatMessage_Image) isChatMessage_Payload() {}

func (*ChatMessage_Voice) isChatMessage_Payload() {}

func (*ChatMessage_Video) isChatMessage_Payload() {}

func (*ChatMessage_File) isChatMessage_Payload() {}

func (*ChatMessage_System) isChatMessage_Payload() {}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageRequest) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type DeliverMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverMessageRequest) Reset() {
	*x = DeliverMessageRequest{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMessageRequest) ProtoMessage() {}

func (x *DeliverMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMessageRequest.ProtoReflect.Descriptor instead.
func (*DeliverMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *DeliverMessageRequest) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type DeliverMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverMessageResponse) Reset() {
	*x = DeliverMessageResponse{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMessageResponse) ProtoMessage() {}

func (x *DeliverMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMessageResponse.ProtoReflect.Descriptor instead.
func (*DeliverMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

type TextPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	MentionUids   []string               `protobuf:"bytes,2,rep,name=mention_uids,json=mentionUids,proto3" json:"mention_uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextPayload) Reset() {
	*x = TextPayload{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextPayload) ProtoMessage() {}

func (x *TextPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextPayload.ProtoReflect.Descriptor instead.
func (*TextPayload) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *TextPayload) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextPayload) GetMentionUids() []string {
	if x != nil {
		return x.MentionUids
	}
	return nil
}

type ImagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ThumbUrl      string                 `protobuf:"bytes,2,opt,name=thumb_url,json=thumbUrl,proto3" json:"thumb_url,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	SizeBytes     int32                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePayload) Reset() {
	*x = ImagePayload{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePayload) ProtoMessage() {}

func (x *ImagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePayload.ProtoReflect.Descriptor instead.
func (*ImagePayload) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *ImagePayload) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImagePayload) GetThumbUrl() string {
	if x != nil {
		return x.ThumbUrl
	}
	return ""
}

func (x *ImagePayload) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImagePayload) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImagePayload) GetSizeBytes() int32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ImagePayload) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type VoicePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Duration      int32                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	SizeBytes     int32                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoicePayload) Reset() {
	*x = VoicePayload{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoicePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoicePayload) ProtoMessage() {}

func (x *VoicePayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoicePayload.ProtoReflect.Descriptor instead.
func (*VoicePayload) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *VoicePayload) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VoicePayload) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VoicePayload) GetSizeBytes() int32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *VoicePayload) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type VideoPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoUrl      string                 `protobuf:"bytes,1,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,2,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	SizeBytes     int32                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Format        string                 `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoPayload) Reset() {
	*x = VideoPayload{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoPayload) ProtoMessage() {}

func (x *VideoPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoPayload.ProtoReflect.Descriptor instead.
func (*VideoPayload) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *VideoPayload) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *VideoPayload) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *VideoPayload) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoPayload) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoPayload) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoPayload) GetSizeBytes() int32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *VideoPayload) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type FilePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	SizeBytes     int32                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePayload) Reset() {
	*x = FilePayload{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePayload) ProtoMessage() {}

func (x *FilePayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePayload.ProtoReflect.Descriptor instead.
func (*FilePayload) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *FilePayload) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FilePayload) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FilePayload) GetSizeBytes() int32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FilePayload) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type SystemPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        SystemPayload_Action   `protobuf:"varint,1,opt,name=action,proto3,enum=proto.SystemPayload_Action" json:"action,omitempty"`
	OperatorId    string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemPayload) Reset() {
	*x = SystemPayload{}
	mi := &file_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemPayload) ProtoMessage() {}

func (x *SystemPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemPayload.ProtoReflect.Descriptor instead.
func (*SystemPayload) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *SystemPayload) GetAction() SystemPayload_Action {
	if x != nil {
		return x.Action
	}
	return SystemPayload_ACTION_UNSPECIFIED
}

func (x *SystemPayload) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *SystemPayload) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *SystemPayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x05proto\"\xf9\x04\n" +
	"\vChatMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\tR\vclientMsgId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x04 \x01(\tR\n" +
	"receiverId\x12,\n" +
	"\tchat_type\x18\x05 \x01(\x0e2\x0f.proto.ChatTypeR\bchatType\x12\x1f\n" +
	"\vserver_time\x18\x06 \x01(\x03R\n" +
	"serverTime\x12(\n" +
	"\x04text\x18\n" +
	" \x01(\v2\x12.proto.TextPayloadH\x00R\x04text\x12+\n" +
	"\x05image\x18\v \x01(\v2\x13.proto.ImagePayloadH\x00R\x05image\x12+\n" +
	"\x05voice\x18\f \x01(\v2\x13.proto.VoicePayloadH\x00R\x05voice\x12+\n" +
	"\x05video\x18\r \x01(\v2\x13.proto.VideoPayloadH\x00R\x05video\x12(\n" +
	"\x04file\x18\x0e \x01(\v2\x12.proto.FilePayloadH\x00R\x04file\x12.\n" +
	"\x06system\x18\x0f \x01(\v2\x14.proto.SystemPayloadH\x00R\x06system\x12%\n" +
	"\x0freply_to_msg_id\x18\x14 \x01(\tR\freplyToMsgId\x12-\n" +
	"\x03ext\x18\x15 \x03(\v2\x1b.proto.ChatMessage.ExtEntryR\x03ext\x1a6\n" +
	"\bExtEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\apayload\"B\n" +
	"\x12SendMessageRequest\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.proto.ChatMessageR\amessage\"C\n" +
	"\x13SendMessageResponse\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.proto.ChatMessageR\amessage\"E\n" +
	"\x15DeliverMessageRequest\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.proto.ChatMessageR\amessage\"\x18\n" +
	"\x16DeliverMessageResponse\"J\n" +
	"\vTextPayload\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12!\n" +
	"\fmention_uids\x18\x02 \x03(\tR\vmentionUids\"\xa2\x01\n" +
	"\fImagePayload\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tthumb_url\x18\x02 \x01(\tR\bthumbUrl\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x05R\tsizeBytes\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\"s\n" +
	"\fVoicePayload\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x05R\bduration\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x05R\tsizeBytes\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"\xc9\x01\n" +
	"\fVideoPayload\x12\x1b\n" +
	"\tvideo_url\x18\x01 \x01(\tR\bvideoUrl\x12\x1b\n" +
	"\tcover_url\x18\x02 \x01(\tR\bcoverUrl\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x05R\tsizeBytes\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\"s\n" +
	"\vFilePayload\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x05R\tsizeBytes\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"\xfd\x01\n" +
	"\rSystemPayload\x123\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1b.proto.SystemPayload.ActionR\x06action\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"e\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACTION_MSG_RECALL\x10\x01\x12\x15\n" +
	"\x11ACTION_GROUP_JOIN\x10\x02\x12\x15\n" +
	"\x11ACTION_GROUP_KICK\x10\x03*`\n" +
	"\bChatType\x12\x15\n" +
	"\x11CHAT_TYPE_INVALID\x10\x00\x12\x14\n" +
	"\x10CHAT_TYPE_SINGLE\x10\x01\x12\x13\n" +
	"\x0fCHAT_TYPE_GROUP\x10\x02\x12\x12\n" +
	"\x0eCHAT_TYPE_ROOM\x10\x032U\n" +
	"\rWorkerService\x12D\n" +
	"\vSendMessage\x12\x19.proto.SendMessageRequest\x1a\x1a.proto.SendMessageResponse2_\n" +
	"\x0eGatewayService\x12M\n" +
	"\x0eDeliverMessage\x12\x1c.proto.DeliverMessageRequest\x1a\x1d.proto.DeliverMessageResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_message_proto_goTypes = []any{
	(ChatType)(0),                  // 0: proto.ChatType
	(SystemPayload_Action)(0),      // 1: proto.SystemPayload.Action
	(*ChatMessage)(nil),            // 2: proto.ChatMessage
	(*SendMessageRequest)(nil),     // 3: proto.SendMessageRequest
	(*SendMessageResponse)(nil),    // 4: proto.SendMessageResponse
	(*DeliverMessageRequest)(nil),  // 5: proto.DeliverMessageRequest
	(*DeliverMessageResponse)(nil), // 6: proto.DeliverMessageResponse
	(*TextPayload)(nil),            // 7: proto.TextPayload
	(*ImagePayload)(nil),           // 8: proto.ImagePayload
	(*VoicePayload)(nil),           // 9: proto.VoicePayload
	(*VideoPayload)(nil),           // 10: proto.VideoPayload
	(*FilePayload)(nil),            // 11: proto.FilePayload
	(*SystemPayload)(nil),          // 12: proto.SystemPayload
	nil,                            // 13: proto.ChatMessage.ExtEntry
}
var file_message_proto_depIdxs = []int32{
	0,  // 0: proto.ChatMessage.chat_type:type_name -> proto.ChatType
	7,  // 1: proto.ChatMessage.text:type_name -> proto.TextPayload
	8,  // 2: proto.ChatMessage.image:type_name -> proto.ImagePayload
	9,  // 3: proto.ChatMessage.voice:type_name -> proto.VoicePayload
	10, // 4: proto.ChatMessage.video:type_name -> proto.VideoPayload
	11, // 5: proto.ChatMessage.file:type_name -> proto.FilePayload
	12, // 6: proto.ChatMessage.system:type_name -> proto.SystemPayload
	13, // 7: proto.ChatMessage.ext:type_name -> proto.ChatMessage.ExtEntry
	2,  // 8: proto.SendMessageRequest.message:type_name -> proto.ChatMessage
	2,  // 9: proto.SendMessageResponse.message:type_name -> proto.ChatMessage
	2,  // 10: proto.DeliverMessageRequest.message:type_name -> proto.ChatMessage
	1,  // 11: proto.SystemPayload.action:type_name -> proto.SystemPayload.Action
	3,  // 12: proto.WorkerService.SendMessage:input_type -> proto.SendMessageRequest
	5,  // 13: proto.GatewayService.DeliverMessage:input_type -> proto.DeliverMessageRequest
	4,  // 14: proto.WorkerService.SendMessage:output_type -> proto.SendMessageResponse
	6,  // 15: proto.GatewayService.DeliverMessage:output_type -> proto.DeliverMessageResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[0].OneofWrappers = []any{
		(*ChatMessage_Text)(nil),
		(*ChatMessage_Image)(nil),
		(*ChatMessage_Voice)(nil),
		(*ChatMessage_Video)(nil),
		(*ChatMessage_File)(nil),
		(*ChatMessage_System)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
