// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchCreateMessages = `-- name: BatchCreateMessages :batchexec
INSERT INTO messages (
    msg_id,
    client_msg_id,
    sender_id,
    receiver_id,
    chat_type,
    msg_type,
    server_time,
    reply_to_msg_id,
    payload,
    ext
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (msg_id) DO NOTHING
`

type BatchCreateMessagesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchCreateMessagesParams struct {
	MsgID        uuid.UUID       `json:"msg_id"`
	ClientMsgID  uuid.UUID       `json:"client_msg_id"`
	SenderID     uuid.UUID       `json:"sender_id"`
	ReceiverID   uuid.UUID       `json:"receiver_id"`
	ChatType     ChatType        `json:"chat_type"`
	MsgType      MessageType     `json:"msg_type"`
	ServerTime   int64           `json:"server_time"`
	ReplyToMsgID *uuid.UUID      `json:"reply_to_msg_id"`
	Payload      json.RawMessage `json:"payload"`
	Ext          json.RawMessage `json:"ext"`
}

func (q *Queries) BatchCreateMessages(ctx context.Context, arg []BatchCreateMessagesParams) *BatchCreateMessagesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.MsgID,
			a.ClientMsgID,
			a.SenderID,
			a.ReceiverID,
			a.ChatType,
			a.MsgType,
			a.ServerTime,
			a.ReplyToMsgID,
			a.Payload,
			a.Ext,
		}
		batch.Queue(batchCreateMessages, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchCreateMessagesBatchResults{br, len(arg), false}
}

func (b *BatchCreateMessagesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchCreateMessagesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
