// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (
    msg_id,
    client_msg_id,
    sender_id,
    receiver_id,
    chat_type,
    server_time,
    reply_to_msg_id,
    payload,
    ext
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type CreateMessageParams struct {
	MsgID        string   `json:"msg_id"`
	ClientMsgID  string   `json:"client_msg_id"`
	SenderID     string   `json:"sender_id"`
	ReceiverID   string   `json:"receiver_id"`
	ChatType     ChatType `json:"chat_type"`
	ServerTime   int64    `json:"server_time"`
	ReplyToMsgID string   `json:"reply_to_msg_id"`
	Payload      []byte   `json:"payload"`
	Ext          []byte   `json:"ext"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.MsgID,
		arg.ClientMsgID,
		arg.SenderID,
		arg.ReceiverID,
		arg.ChatType,
		arg.ServerTime,
		arg.ReplyToMsgID,
		arg.Payload,
		arg.Ext,
	)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT
    msg_id,
    client_msg_id,
    sender_id,
    receiver_id,
    chat_type,
    server_time,
    reply_to_msg_id,
    payload,
    ext,
    created_at
FROM messages
WHERE msg_id = $1
LIMIT 1
`

func (q *Queries) GetMessageByID(ctx context.Context, msgID string) (*Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, msgID)
	var i Message
	err := row.Scan(
		&i.MsgID,
		&i.ClientMsgID,
		&i.SenderID,
		&i.ReceiverID,
		&i.ChatType,
		&i.ServerTime,
		&i.ReplyToMsgID,
		&i.Payload,
		&i.Ext,
		&i.CreatedAt,
	)
	return &i, err
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT
    msg_id,
    client_msg_id,
    sender_id,
    receiver_id,
    chat_type,
    server_time,
    reply_to_msg_id,
    payload,
    ext,
    created_at
FROM messages
WHERE receiver_id = $1
  AND chat_type = $2
  AND server_time < $3
ORDER BY server_time DESC
LIMIT $4
`

type ListMessagesByConversationParams struct {
	ReceiverID       string   `json:"receiver_id"`
	ChatType         ChatType `json:"chat_type"`
	BeforeServerTime int64    `json:"before_server_time"`
	PageSize         int32    `json:"page_size"`
}

func (q *Queries) ListMessagesByConversation(ctx context.Context, arg ListMessagesByConversationParams) ([]*Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversation,
		arg.ReceiverID,
		arg.ChatType,
		arg.BeforeServerTime,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.MsgID,
			&i.ClientMsgID,
			&i.SenderID,
			&i.ReceiverID,
			&i.ChatType,
			&i.ServerTime,
			&i.ReplyToMsgID,
			&i.Payload,
			&i.Ext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
