// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChatType string

const (
	ChatTypeSingle ChatType = "single"
	ChatTypeGroup  ChatType = "group"
	ChatTypeRoom   ChatType = "room"
)

func (e *ChatType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatType(s)
	case string:
		*e = ChatType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatType: %T", src)
	}
	return nil
}

type NullChatType struct {
	ChatType ChatType `json:"chat_type"`
	Valid    bool     `json:"valid"` // Valid is true if ChatType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatType) Scan(value interface{}) error {
	if value == nil {
		ns.ChatType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatType), nil
}

type Message struct {
	MsgID        string             `json:"msg_id"`
	ClientMsgID  string             `json:"client_msg_id"`
	SenderID     string             `json:"sender_id"`
	ReceiverID   string             `json:"receiver_id"`
	ChatType     ChatType           `json:"chat_type"`
	ServerTime   int64              `json:"server_time"`
	ReplyToMsgID string             `json:"reply_to_msg_id"`
	Payload      []byte             `json:"payload"`
	Ext          []byte             `json:"ext"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
