// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	GetMessageByID(ctx context.Context, msgID string) (*Message, error)
	ListMessagesByConversation(ctx context.Context, arg ListMessagesByConversationParams) ([]*Message, error)
}

var _ Querier = (*Queries)(nil)
