name: backend-bench

on:
  push:
    paths:
      - ".github/workflows/backend-bench.yml"
      - "backend/**"
  pull_request:
    paths:
      - ".github/workflows/backend-bench.yml"
      - "backend/**"
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Set up PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v8
        id: postgres

      - name: Run database migrations
        run: psql ${{ steps.postgres.outputs.connection-uri }} -f db/migrations/migrate.sql