name: sdk测试
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  sdk-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up Backend
        run: docker compose up -d
          
      - name: Run SDK tests
        run: |
          cd sdk
          pnpm test &> test.log || true 
          
          echo "### 📄 Test Logs" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat test.log >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        env:
          API_BASE_URL: http://localhost:8801
          WS_GATEWAY_URL: ws://localhost:8800/ws